### ISSUE TITLE
Callback is broken

### ISSUE THREAD

**Issue by colt05-usr** [colt05/ignore#2]
TypeError: cb is not a function
at iterate (/app/app.js:154:5)
at iterate (/app/app.js:158:5)
at iterate (/app/app.js:158:5)
at iterate (/app/app.js:158:5)
at iterate (/app/app.js:158:5)
at iterate (/app/app.js:158:5)
 at iterate (/app/app.js:158:5)
 at iterate (/app/app.js:158:5)
at iterate (/app/app.js:158:5)
at iterate2 (/app/app.js:174:5)

...and so on.

**Comment by colt05-usr** [comment]
Fixed @ https://github.com/colt05/ignore/commit/77cb7f6c0ee39321435419785a917035fb2ece36
